version: '3.1'

services:
  # Servicio de la base de datos MongoDB
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Servicio de la aplicación Node.js con Express
  node_app:
    container_name: node-app
    build:
      context: ./node-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/myapp_db
