POST http://192.168.1.72:3000/api/v2/audiencia/login
Content-Type: application/json

{
    "NombreUsuario": "Alex",
    "Password": "1234567890"
}

###
POST http://localhost:3000/api/v2/audiencia
Content-Type: application/json

{
    "Correo": "correo@ejemplo.com", 
    "NombreUsuario": "nombreDeUsuario",
    "Password": "contraseña",
    "NumeroTelefonico": "1234567890",
    "Canciones": []
}

### 

PUT http://localhost:3000/api/v2/audiencia/Alex
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjY1ZTcwMzk3NzA0NDI0YTliNWYyMDciLCJOb21icmVVc3VhcmlvIjoiQWxleCIsIkNvcnJlbyI6ImFhdnAxNjAyQGhvdG1haWwuY29tIiwiVXNlclR5cGUiOiJBdWRpZW5jaWEiLCJpYXQiOjE3MTc5NTcyNjcsImV4cCI6MTcxNzk1OTA2N30.XmT-2afcVtORE91gVxsIsQJW5eC7wRi5gck5P9JcWts

{
    "Correo": "aavp0414@hotmail.com",
    "NumeroTelefonico": "1245789638"
}



### 

DELETE http://localhost:3000/api/v2/audiencia/nombreUsuarioPrueba
Authorization: Bearer <TU_TOKEN_JWT>
