POST http://localhost:3000/api/v2/audiencia/login
Content-Type: application/json

{
    "NombreUsuario": "nombreDeUsuario",
    "Password": "contraseña"
}

###
POST http://localhost:3000/api/v2/audiencia
Content-Type: application/json

{
    "Correo": "correo@ejemplo.com", 
    "NombreUsuario": "nombreDeUsuario",
    "Password": "contraseña",
    "NumeroTelefonico": "1234567890",
    "Canciones": []
}

### 

PUT http://localhost:3000/api/v2/audiencia/nombreDeUsuario
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjViZmYwODhkYzQ1YmM0NGExY2UzYjMiLCJOb21icmVVc3VhcmlvIjoibm9tYnJlRGVVc3VhcmlvIiwiQ29ycmVvIjoiY29ycmVvQGVqZW1wbG8uY29tIiwiaWF0IjoxNzE3MzA1NzI4LCJleHAiOjE3MTczMDc1Mjh9.ntCvgmDFSr9fLYdDxvrhIiwcngz9RtuRtguLQ3a5lXM

{
    "Correo": "correo@prueba.com",
    "Password": "nuevaPassword2",
    "NumeroTelefonico": "9876543210"
}



### 

DELETE http://localhost:3000/api/v2/audiencia/nombreUsuarioPrueba
Authorization: Bearer <TU_TOKEN_JWT>
