POST http://localhost:3000/api/v2/audiencia/login
Content-Type: application/json

{
    "NombreUsuario": "usuario1",
    "Password": "password1"
}


### Crear un nuevo usuario (POST)

POST http://localhost:3000/api/v2/audiencia
Content-Type: application/json

{
    "Correo": "correo@ejemplo.com",
    "NombreUsuario": "nombreDeUsuario",
    "Password": "contraseña",
    "NumeroTelefonico": "1234567890",
    "Canciones": []
}

### Actualizar información de usuario existente (PUT)

PUT http://localhost:3000/api/v2/audiencia/nombreUsuarioPrueba
Content-Type: application/json

{
    "Correo": "correo@prueba.com",
    "Password": "nuevaPassword",
    "NumeroTelefonico": "9876543210"
}

### Eliminar usuario (DELETE)

DELETE http://localhost:3000/api/v2/audiencia/nombreUsuarioPrueba
